// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiruYJqywi3g354BkL5hNM3Rc5sm9KfoA',
    appId: '1:265972319969:web:d03ab98a27f09bdf7f59a0',
    messagingSenderId: '265972319969',
    projectId: 'tsvmanager-e23a9',
    authDomain: 'tsvmanager-e23a9.firebaseapp.com',
    storageBucket: 'tsvmanager-e23a9.appspot.com',
    measurementId: 'G-D5DQKDMES1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCAQcbPZCpre0Ybe9GC-RDU4WLtDWx_nM',
    appId: '1:265972319969:android:04832ae5dd0d4daf7f59a0',
    messagingSenderId: '265972319969',
    projectId: 'tsvmanager-e23a9',
    storageBucket: 'tsvmanager-e23a9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtxOnawcS_Hx0XUYNEAjMuSbXSXsdFAaU',
    appId: '1:265972319969:ios:1ee533e3735c36957f59a0',
    messagingSenderId: '265972319969',
    projectId: 'tsvmanager-e23a9',
    storageBucket: 'tsvmanager-e23a9.appspot.com',
    iosClientId: '265972319969-jpirr91oc8s26raqvlb8f4aqcceo71cg.apps.googleusercontent.com',
    iosBundleId: 'com.example.tsvManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtxOnawcS_Hx0XUYNEAjMuSbXSXsdFAaU',
    appId: '1:265972319969:ios:1ee533e3735c36957f59a0',
    messagingSenderId: '265972319969',
    projectId: 'tsvmanager-e23a9',
    storageBucket: 'tsvmanager-e23a9.appspot.com',
    iosClientId: '265972319969-jpirr91oc8s26raqvlb8f4aqcceo71cg.apps.googleusercontent.com',
    iosBundleId: 'com.example.tsvManager',
  );
}
