// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWrgfN9G-xVLe7AEpkZO0i4uaeEc9ruzs',
    appId: '1:223055563717:web:32a2895c623c34615959ac',
    messagingSenderId: '223055563717',
    projectId: 'liv2gether-eva',
    authDomain: 'liv2gether-eva.firebaseapp.com',
    storageBucket: 'liv2gether-eva.appspot.com',
    measurementId: 'G-BKDHX068CC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgvYCOnL5-fEZvKgxbvJkK3eWOuVWW9Z4',
    appId: '1:223055563717:android:611c6ab634673b3c5959ac',
    messagingSenderId: '223055563717',
    projectId: 'liv2gether-eva',
    storageBucket: 'liv2gether-eva.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVNCn8O_4tuhpkbay-9K0P9EZeA5j3Isc',
    appId: '1:223055563717:ios:d0a91d87c3e200895959ac',
    messagingSenderId: '223055563717',
    projectId: 'liv2gether-eva',
    storageBucket: 'liv2gether-eva.appspot.com',
    iosClientId: '223055563717-6sbog6l93f1kr9d6bvaraa1feq3jia46.apps.googleusercontent.com',
    iosBundleId: 'de.thm.wgApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVNCn8O_4tuhpkbay-9K0P9EZeA5j3Isc',
    appId: '1:223055563717:ios:6b837d5fc878601d5959ac',
    messagingSenderId: '223055563717',
    projectId: 'liv2gether-eva',
    storageBucket: 'liv2gether-eva.appspot.com',
    iosClientId: '223055563717-12if5dspiu7i7ktqrg9l3vqr3uc1mt8p.apps.googleusercontent.com',
    iosBundleId: 'de.thm.wgApp.RunnerTests',
  );
}
